trigger:
 branches:
   include:
     - main
pool:
  vmImage: windows-latest
  
variables:
  artifactName: 'drop'


stages:
  - stage: Build
    jobs:
      - job: "Detect"
        steps:
          - checkout: self
          - task: PowerShell@2
            displayName: 'Detect changes in wp-content'
            inputs:
              targetType: 'inline'
              script: |
                #Get any changed files
                git fetch origin main
                 $changedFiles = git diff --name-status HEAD HEAD^ 
                 Write-Host "changed-files:`n$changedFiles"
                
                # Return $true if Files/ path is in the list of changed files, otherwise $false
                $filesChanged = ((Select-String -InputObject $changedFiles -Pattern "wp-content/" -AllMatches).Matches.Count -gt 0)
                Write-Host "changed-files-wp-content:`n$filesChanged"
                # # Fetch full history of current branch for usage in git diff
                # git fetch origin $(git rev-parse HEAD) --unshallow
                # git fetch origin main

                # # Get a list of files changed by this branch compared to origin/main
                # $changedFiles = git diff origin/main...HEAD --name-only
                #     Write-Host "Changed files:`n$changedFiles"

                # if ($changedFiles -match "^wp-content/") {
                #     Write-Host "##vso[task.setvariable variable=WpContentChanged]true"
                # } else {
                #     Write-Host "##vso[task.setvariable variable=WpContentChanged]false"
                # }
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'
            condition: eq(variables['WpContentChanged'], 'true')
          - script: |
              cd wp-content/themes/RSNE
              npm install
              npm run build

            displayName: 'npm install and build'
  #         - task: ArchiveFiles@2
  #           inputs:
  #             rootFolderOrFile: '$(Build.SourcesDirectory)'
  #             includeRootFolder: true
  #             archiveType: 'zip'
  #             archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  #             replaceExistingArchive: true
  #         - task: PublishBuildArtifacts@1
  #           inputs:
  #             PathtoPublish: '$(Build.ArtifactStagingDirectory)'
  #             ArtifactName: '$(artifactName)'
  #             publishLocation: 'Container'

  # - stage: Deploy
  #   dependsOn: Build
  #   condition: succeeded()
  #   jobs:
  #     - job: "Deploy"
  #       steps:
  #         - task: ExtractFiles@1
  #           inputs:
  #             archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  #             destinationFolder: '$(System.DefaultWorkingDirectory)/extracted'
  #             cleanDestinationFolder: true
  #             overwriteExistingFiles: false
  #         - script: |
  #             mv $(System.DefaultWorkingDirectory)/extracted/s/* $(System.DefaultWorkingDirectory)/extracted/
  #             rmdir $(System.DefaultWorkingDirectory)/extracted/s
  #           displayName: 'Move files from "s" folder'
  #         - task: AzureWebApp@1
  #           inputs:
  #             azureSubscription: 'Sample'
  #             appType: 'webAppLinux'
  #             appName: wordpressdem
  #             resourceGroupName: rsne-demo
  #             package: '$(System.DefaultWorkingDirectory)/extracted'