trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  artifactName: 'drop'

stages:
  - stage: Build
    jobs:
      - job: "Detect"
        steps:
          - checkout: self
          - script: |
              folders=("wp-content")
              changed=true
              echo "Enter into Script"

              # Make sure we have the latest info about origin/main
              git fetch origin main
              echo "Fetched the main branch"

              # Check if *any file outside* the monitored folders has changed
              if git diff --name-only origin/main HEAD | grep -q "^$folder/"; then
                  echo "Changes detected outside monitored folders."
                  changed=false
              else
                  echo "All changes are within monitored folders."
              fi

              # Decision based on folder changes
              if [ "$changed" = true ]; then
                  echo "Proceeding with triggering Azure Pipeline."
                  # Trigger your pipeline here
              else
                  echo "No changes detected in monitored folders. Skipping pipeline trigger."
              fi




            displayName: "Detect wp-content Changes"
  #         - task: NodeTool@0
  #           inputs:
  #             versionSpec: '20.x'
  #           displayName: 'Install Node.js'

  #         - script: |
  #             cd wp-content/themes/RSNE
  #             npm install
  #             npm run build
  #           condition: eq(variables['wpContentChanged'], 'true')
  #           displayName: 'npm install and build'
  #         - task: ArchiveFiles@2
  #           inputs:
  #             rootFolderOrFile: '$(Build.SourcesDirectory)'
  #             includeRootFolder: true
  #             archiveType: 'zip'
  #             archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  #             replaceExistingArchive: true
  #         - task: PublishBuildArtifacts@1
  #           inputs:
  #             PathtoPublish: '$(Build.ArtifactStagingDirectory)'
  #             ArtifactName: '$(artifactName)'
  #             publishLocation: 'Container'

  # - stage: Deploy
  #   dependsOn: Build
  #   condition: succeeded()
  #   jobs:
  #     - job: "Deploy"
  #       steps:
  #         - task: ExtractFiles@1
  #           inputs:
  #             archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  #             destinationFolder: '$(System.DefaultWorkingDirectory)/extracted'
  #             cleanDestinationFolder: true
  #             overwriteExistingFiles: false
  #         - script: |
  #             mv $(System.DefaultWorkingDirectory)/extracted/s/* $(System.DefaultWorkingDirectory)/extracted/
  #             rmdir $(System.DefaultWorkingDirectory)/extracted/s
  #           displayName: 'Move files from "s" folder'
  #         - task: AzureWebApp@1
  #           inputs:
  #             azureSubscription: 'Sample'
  #             appType: 'webAppLinux'
  #             appName: wordpressdem
  #             resourceGroupName: rsne-demo
  #             package: '$(System.DefaultWorkingDirectory)/extracted'